import Head from "next/head";
import Image from "next/image";
import styles from "~/styles/Home.module.css";
import AppHeader from '~/components/AppHeader/AppHeader';
import PromoSection from '~/components/PromoSection/PromoSection';
import ProductSection from '~/components/ProductSection/ProductSection';
import ContactSection from '~/components/ContactSection/ContactSection';
import AppFooter from '~/components/AppFooter/AppFooter';

export default function Home() {
    return (
        <div className={styles.bodyContainer}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta name="viewport" content="width=1280"></meta>
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;700&display=swap" rel="stylesheet" />
            </Head>

            <AppHeader className={styles.bodyHeader} />
            <PromoSection />
            <ProductSection />
            <ContactSection />
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d1888041.8372930004!2d114.00929041663805!3d22.44476421276827!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2sru!4v1619970972365!5m2!1sru!2sru" width="100%" height="450" allowfullscreen="" loading="lazy"></iframe>
            <AppFooter />
        </div>
    );
}
